definitions:
  model.Category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: ginblog项目
  license: {}
  termsOfService: https://github.com/jeffygu/ginblog
  title: ginblog系统
  version: "1.0"
paths:
  /api/v1/categorys:
    get:
      parameters:
      - description: 分类名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: pagenum
        type: integer
      - description: 每页数量
        in: query
        name: pagesize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Category'
      summary: 获取分类列表
  /api/v1/categorys/add:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Category'
      summary: 添加分类
swagger: "2.0"
